/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "home": [],
    "search": [],
    "works.show": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "student.dashboard": [],
    "student.works.index": [],
    "student.works.create": [],
    "student.works.store": [],
    "student.works.show": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "student.works.edit": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "student.works.update": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "student.works.destroy": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "student.works.submit": [
        {
            "name": "work",
            "required": true
        }
    ],
    "lecturer.dashboard": [],
    "lecturer.reviews.pending": [],
    "lecturer.reviews.show": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "lecturer.reviews.approve": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "lecturer.reviews.reject": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "lecturer.reviews.revision": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "lecturer.reviews.history": [],
    "lecturer.works.preview": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.dashboard": [],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.works.index": [],
    "admin.works.show": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.works.publish": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.works.destroy": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.works.trashed": [],
    "admin.works.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.works.force-delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.departments.index": [],
    "admin.departments.create": [],
    "admin.departments.store": [],
    "admin.departments.show": [
        {
            "name": "department",
            "required": true
        }
    ],
    "admin.departments.edit": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.work-categories.index": [],
    "admin.work-categories.create": [],
    "admin.work-categories.store": [],
    "admin.work-categories.show": [
        {
            "name": "work_category",
            "required": true
        }
    ],
    "admin.work-categories.edit": [
        {
            "name": "work_category",
            "required": true
        }
    ],
    "admin.work-categories.update": [
        {
            "name": "work_category",
            "required": true
        }
    ],
    "admin.work-categories.destroy": [
        {
            "name": "work_category",
            "required": true
        }
    ],
    "admin.reports.index": [],
    "admin.reports.works": [],
    "admin.reports.users": [],
    "admin.reports.export": [],
    "works.preview": [
        {
            "name": "work",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
